sudo: required
services:
  - docker

before_install:
  - docker build -t adrianstru/docker-react -f Dockerfile.dev .

script:
  - docker run adrianstru/docker-react yarn test-ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-268468753194"
  bucket_path: "docker"
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"